spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sportgram
    username: root
    password: 419914